digital/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\FrontSettingController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\ProvideServiceController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\GalleryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/',[HomeController::class,'index'])->name('index');
Route::get('our-services',[HomeController::class,'ourService'])->name('our-services');
Route::get('about-us',[HomeController::class,'aboutUs'])->name('about-us');
Route::get('contactus',[HomeController::class,'contactUs'])->name('contactUs');
Route::get('client',[HomeController::class,'client'])->name('client');
Route::get('galleries',[HomeController::class,'gallery'])->name('galleries');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

// front settings
Route::get('setting/home', [FrontSettingController::class, 'home'])->name('front.settings.home');
Route::post('setting/home', [FrontSettingController::class, 'homeUpdate'])->name('front.settings.home.update');
Route::delete('delete-home-slider/{homePageSlider}', [FrontSettingController::class, 'deleteHomeSlider'])->name('front.settings.deleteHomeSlider');
//Route::get('get-home-hero-images',[FrontSettingController::class, 'getHomeHeroImages'])->name('get.home.hero.images');


// settings routes
Route::get('settings', [SettingController::class,'index'])->name('settings.index');
Route::post('settings', [SettingController::class,'update'])->name('settings.update');


Route::resource('provide-services', ProvideServiceController::class);
Route::post('provide-services/{provide_service}/update', [ProvideServiceController::class,'update']);

Route::resource('clients', ClientController::class);
Route::post('clients/{client}/update', [ClientController::class,'update']);

Route::resource('contact-us', ContactUsController::class);

Route::resource('gallery', GalleryController::class);
Route::post('gallery/{gallery}/update', [GalleryController::class,'update']);

digital/resources/views/theme/about.blade.php
@extends('theme.layout.app')
@section('title')
    About Us
@endsection

@section('content')
<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
        <div class="container animate__animated animate__bounce">

            <ol>
                <li><a href="{{ url('/') }}">Home</a></li>
                <li>About Us</li>
            </ol>
            <h2>About Us</h2>

        </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
        <div class="container">

            <div class="row">
                <div class="col-lg-6 hvr-float-shadow">
                    <img src="assets/img/about.jpg" class="img-fluid " alt="">
                </div>
                <div class="col-lg-6 pt-4 pt-lg-0 content">
                    <h3 class="animate__animated animate__bounce">Voluptatem dignissimos provident quasi corporis voluptates sit assumenda.</h3>
                    <p class="font-italic">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
                        magna aliqua.
                    </p>
                    <ul>
                        <li><i class="icofont-check-circled"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>
                        <li><i class="icofont-check-circled"></i> Duis aute irure dolor in reprehenderit in voluptate velit.</li>
                        <li><i class="icofont-check-circled"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate trideta storacalaperda mastiro dolore eu fugiat nulla pariatur.</li>
                    </ul>
                    <p>
                        Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
                        velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
                        culpa qui officia deserunt mollit anim id est laborum
                    </p>
                </div>
            </div>

        </div>
    </section><!-- End About Section -->

    <!-- ======= Counts Section ======= -->
    <section id="counts" class="counts">
        <div class="container">

            <div class="row no-gutters">

                <div class="col-lg-3 col-md-6 d-md-flex align-items-md-stretch hvr-bounce-in hvr-shadow-radial">
                    <div class="count-box" data-aos="fade-up"
                         data-aos-anchor-placement="center-bottom">
                        <i class="icofont-simple-smile"></i>
                        <span data-toggle="counter-up">232</span>
                        <p><strong>Happy Clients</strong> consequuntur quae qui deca rode</p>
                        <a href="#">Find out more &raquo;</a>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 d-md-flex align-items-md-stretch hvr-bounce-in hvr-shadow-radial">
                    <div class="count-box" data-aos="fade-up"
                         data-aos-duration="1000"
                         data-aos-anchor-placement="center-bottom">
                        <i class="icofont-document-folder"></i>
                        <span data-toggle="counter-up">521</span>
                        <p><strong>Projects</strong> adipisci atque cum quia aut numquam delectus</p>
                        <a href="#">Find out more &raquo;</a>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 d-md-flex align-items-md-stretch hvr-bounce-in hvr-shadow-radial">
                    <div class="count-box" data-aos="fade-up"
                         data-aos-duration="1000"
                         data-aos-anchor-placement="center-bottom">
                        <i class="icofont-live-support"></i>
                        <span data-toggle="counter-up">1,463</span>
                        <p><strong>Hours Of Support</strong> aut commodi quaerat. Aliquam ratione</p>
                        <a href="#">Find out more &raquo;</a>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 d-md-flex align-items-md-stretch hvr-bounce-in hvr-shadow-radial">
                    <div class="count-box" data-aos="fade-up"
                         data-aos-duration="1000"
                         data-aos-anchor-placement="center-bottom">
                        <i class="icofont-users-alt-5"></i>
                        <span data-toggle="counter-up">15</span>
                        <p><strong>Hard Workers</strong> rerum asperiores dolor molestiae doloribu</p>
                        <a href="#">Find out more &raquo;</a>
                    </div>
                </div>

            </div>

        </div>
    </section><!-- End Counts Section -->

    <!-- ======= Clients Section ======= -->
    <section id="clients" class="clients">
        <div class="container">

            <div class="section-title" data-aos="fade-up"
                 data-aos-duration="1000"
                 data-aos-anchor-placement="center-bottom">
                <h2>Clients</h2>
                <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
            </div>

            <div class="owl-carousel clients-carousel" data-aos="fade-up"
                 data-aos-duration="1000"
                 data-aos-anchor-placement="center-bottom">
                <img src="assets/img/clients/client-1.png" alt="">
                <img src="assets/img/clients/client-2.png" alt="">
                <img src="assets/img/clients/client-3.png" alt="">
                <img src="assets/img/clients/client-4.png" alt="">
                <img src="assets/img/clients/client-5.png" alt="">
                <img src="assets/img/clients/client-6.png" alt="">
                <img src="assets/img/clients/client-7.png" alt="">
                <img src="assets/img/clients/client-8.png" alt="">
            </div>

        </div>
    </section><!-- End Clients Section -->

    <!-- ======= Testimonials Section ======= -->
    <section id="testimonials" class="testimonials" data-aos="fade-up"
             data-aos-duration="1000"
             data-aos-anchor-placement="center-bottom">
        <div class="container">

            <div class="section-title ">
                <h2>Testimonials</h2>
                <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
            </div>

            <div class="row">

                <div class="col-lg-6">
                    <div class="testimonial-item" data-aos="fade-up"
                         data-aos-duration="1000"
                         data-aos-anchor-placement="center-bottom">
                        <img src="assets/img/testimonials/testimonials-1.jpg" class="testimonial-img" alt="">
                        <h3>Saul Goodman</h3>
                        <h4>Ceo &amp; Founder</h4>
                        <p>
                            <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                            Proin iaculis purus consequat sem cure digni ssim donec porttitora entum suscipit rhoncus. Accusantium quam, ultricies eget id, aliquam eget nibh et. Maecen aliquam, risus at semper.
                            <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                        </p>
                    </div>
                </div>

                <div class="col-lg-6">
                    <div class="testimonial-item  mt-4 mt-lg-0" data-aos="fade-up"
                         data-aos-duration="1000"
                         data-aos-anchor-placement="center-bottom">
                        <img src="assets/img/testimonials/testimonials-2.jpg" class="testimonial-img" alt="">
                        <h3>Sara Wilsson</h3>
                        <h4>Designer</h4>
                        <p>
                            <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                            Export tempor illum tamen malis malis eram quae irure esse labore quem cillum quid cillum eram malis quorum velit fore eram velit sunt aliqua noster fugiat irure amet legam anim culpa.
                            <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                        </p>
                    </div>
                </div>

                <div class="col-lg-6">
                    <div class="testimonial-item mt-4" data-aos="fade-up"
                         data-aos-duration="1000"
                         data-aos-anchor-placement="center-bottom">
                        <img src="assets/img/testimonials/testimonials-3.jpg" class="testimonial-img" alt="">
                        <h3>Jena Karlis</h3>
                        <h4>Store Owner</h4>
                        <p>
                            <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                            Enim nisi quem export duis labore cillum quae magna enim sint quorum nulla quem veniam duis minim tempor labore quem eram duis noster aute amet eram fore quis sint minim.
                            <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                        </p>
                    </div>
                </div>

                <div class="col-lg-6">
                    <div class="testimonial-item mt-4" data-aos="fade-up"
                         data-aos-duration="1000"
                         data-aos-anchor-placement="center-bottom">
                        <img src="assets/img/testimonials/testimonials-4.jpg" class="testimonial-img" alt="">
                        <h3>Matt Brandon</h3>
                        <h4>Freelancer</h4>
                        <p>
                            <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                            Fugiat enim eram quae cillum dolore dolor amet nulla culpa multos export minim fugiat minim velit minim dolor enim duis veniam ipsum anim magna sunt elit fore quem dolore labore illum veniam.
                            <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                        </p>
                    </div>
                </div>

                <div class="col-lg-6">
                    <div class="testimonial-item mt-4" data-aos="fade-up"
                         data-aos-duration="1000"
                         data-aos-anchor-placement="center-bottom">
                        <img src="assets/img/testimonials/testimonials-5.jpg" class="testimonial-img" alt="">
                        <h3>John Larson</h3>
                        <h4>Entrepreneur</h4>
                        <p>
                            <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                            Quis quorum aliqua sint quem legam fore sunt eram irure aliqua veniam tempor noster veniam enim culpa labore duis sunt culpa nulla illum cillum fugiat legam esse veniam culpa fore nisi cillum quid.
                            <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                        </p>
                    </div>
                </div>

                <div class="col-lg-6">
                    <div class="testimonial-item mt-4" data-aos="fade-up"
                         data-aos-duration="1000"
                         data-aos-anchor-placement="center-bottom">
                        <img src="assets/img/testimonials/testimonials-6.jpg" class="testimonial-img" alt="">
                        <h3>Emily Harison</h3>
                        <h4>Store Owner</h4>
                        <p>
                            <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                            Eius ipsam praesentium dolor quaerat inventore rerum odio. Quos laudantium adipisci eius. Accusamus qui iste cupiditate sed temporibus est aspernatur. Sequi officiis ea et quia quidem.
                            <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                        </p>
                    </div>
                </div>

            </div>

        </div>
    </section><!-- End Testimonials Section -->

</main><!-- End #main -->
@endsection

digital/resources/views/theme/client.blade.php
@extends('theme.layout.app')
@section('title')
    Clients
@endsection
@push('css')
    <link rel="stylesheet" href="{{ mix('assets/css/web/gallery.css')}}">
@endpush
@section('content')
    <main id="main">
        <!-- ======= Breadcrumbs ======= -->
        <section id="breadcrumbs" class="breadcrumbs">
            <div class="container animate__animated animate__bounce">
                <ol>
                    <li><a href="{{ url('/') }}">Home</a></li>
                    <li>Client</li>
                </ol>
                <h2>Client</h2>
            </div>
        </section>
        <!-- End Breadcrumbs -->

        <section id="clientSection" class="clientSection">
            <div class="container">
                <div class="row">
                    @foreach($clients as $client)
                        <div class="col-lg-3 mx-3 d-flex justify-content-center " data-aos="{{ $loop->odd ? 'zoom-out-left' : 'zoom-out-right' }}"  style="margin-bottom:60px; padding-left:0px;padding-right:0px;">
                            <div class="icon-box hvr-pulse">
                                <img src="{{ $client->logo_url }}" style="border-radius: 10px;width: 100%;height:100%;">
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </section>
    </main>
@endsection

digital/resources/views/theme/contact_us.blade.php
@extends('theme.layout.app')
@section('title')
    Contact Us
@endsection

@section('content')
<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
        <div class="container animate__animated animate__bounce">

            <ol>
                <li><a href="{{ url('/') }}">Home</a></li>
                <li>Contact</li>
            </ol>
            <h2>Contact</h2>

        </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
        <div class="container">

            <div class="row">
                <div class="col-lg-6 hvr-wobble-horizontal">
                    <div class="info-box mb-4"  data-aos="flip-left"
                         data-aos-duration="1000">
                        <i class="bx bx-map"></i>
                        <h3>Our Address</h3>
                        <p>{!! $setting['address'] !!}</p>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 hvr-wobble-horizontal">
                    <div class="info-box  mb-4" data-aos="flip-up"  data-aos-duration="1000" data-aos-easing="ease-in-sine">
                        <i class="bx bx-envelope"></i>
                        <h3>Email Us</h3>
                        <p>{{ $setting['email'] }}</p>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 hvr-wobble-horizontal">
                    <div class="info-box  mb-4" data-aos="flip-right" data-aos-duration="1000" data-aos-easing="ease-in-sine">
                        <i class="bx bx-phone-call"></i>
                        <h3>Call Us</h3>
                        <p>{{ $setting['phone']}}</p>
                    </div>
                </div>

            </div>

            <div class="row">

                <div class="col-lg-6 hvr-wobble-horizontal">
                    <iframe src="{{ $frontSetting['map_location'] }}" frameborder="0" style="border:0; width: 100%; height: 384px;" allowfullscreen></iframe>
                </div>

                <div class="col-lg-6" data-aos-duration="1000" data-aos="flip-up">
                    @if (Session::has('success'))
                        <div class="alert alert-success">
                            {{ Session('success') }}
                        </div>
                    @endif
                    @include('flash::message')
                    <form action="{{ route('contact-us.store') }}" method="post" role="form" class="contact-us-form">
                        @csrf
                        <div class="row" >
                            <div class="col-md-6 form-group">
                                <input type="text" name="name" class="form-control {{ $errors->has('name') ? ' is-invalid' : '' }}" value="{{ old('name') }}" id="name" autofocus placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                                @if ($errors->has('name'))
                                    <span class="invalid feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}.</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="col-md-6 form-group mt-3 mt-md-0">
                                <input type="email" class="form-control {{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" autofocus id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                                @if ($errors->has('email'))
                                    <span class="invalid feedback" role="alert">
                                        <strong>{{ $errors->first('email') }}.</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group mt-3">
                            <input type="text" class="form-control{{ $errors->has('subject') ? ' is-invalid' : '' }}" name="subject" value="{{ old('subject') }}" autofocus id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                            @if ($errors->has('subject'))
                                <span class="invalid feedback" role="alert">
                                    <strong>{{ $errors->first('subject') }}.</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group mt-3">
                            <textarea class="form-control{{ $errors->has('message') ? ' is-invalid' : '' }}" name="message" rows="5"  autofocus data-rule="required" data-msg="Please write something for us" placeholder="Message">{{ old('message') }}</textarea>
                            @if ($errors->has('message'))
                                <span class="invalid feedback" role="alert">
                                    <strong>{{ $errors->first('message') }}.</strong>
                                </span>
                            @endif
                        </div>
                        <div class="mb-3">
                            <div class="loading">Loading</div>
                            <div class="sent-message">Your message has been sent. Thank you!</div>
                        </div>
                        <div class="text-center">
                            <button type="submit">Send Message</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- End Contact Section -->

</main><!-- End #main -->
@endsection

digital/resources/views/theme/gallery.blade.php
@extends('theme.layout.app')
@section('title')
    Gallery
@endsection
@push('css')
    <link rel="stylesheet" href="{{ mix('assets/css/web/gallery.css')}}">
@endpush
@section('content')
<main id="main">
    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
        <div class="container animate__animated animate__bounce">
            <ol>
                <li><a href="{{ url('/') }}">Home</a></li>
                <li>Gallery</li>
            </ol>
            <h2 class="animate__animated animate__bounce">Gallery</h2>
        </div>
    </section>
    <!-- End Breadcrumbs -->

    <section id="gallerySection" data-aos="fade-up" class="gallerySection">
        <div class="container">
            <div class="row">
                @foreach($galleries as $gallery)
                    <div data-aos="{{ $loop->odd ? 'fade-up-left' : 'fade-up-right' }}"  class=" col-lg-3 mx-3" style="margin-bottom:60px; padding-left:0px;padding-right:0px;">
                        <div class="icon-box hvr-grow-shadow">
                            <img src="{{ $gallery->image_url }}" style="border-radius: 10px;width: 100%;height: 100%;">
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </section>
</main>
@endsection

digital/resources/views/theme/home.blade.php
@extends('theme.layout.app')

@section('content')

<!-- ======= Hero Section ======= -->
<section id="hero">
    <div class="hero-container">
        <div id="heroCarousel" data-bs-interval="5000" class="carousel slide carousel-fade" data-bs-ride="carousel">

            <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

            <div class="carousel-inner" role="listbox">
                <!-- Slide 1 -->
                @foreach($homeImageSliders as $homeImage)
                    <div class="carousel-item {{ $loop->first ? 'active' : '' }}">
                        <div class="carousel-container">
                            <div class="carousel-content">
                                <img src="{{ $homeImage->name }}">
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>

            <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
                <span class="carousel-control-prev-icon icofont-rounded-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>

            <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
                <span class="carousel-control-next-icon icofont-rounded-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>

        </div>
    </div>
</section><!-- End Hero -->

<main id="main" style="margin-top: 13%">

    <!-- ======= Featured Section ======= -->
{{--    <section id="featured" class="featured">--}}
{{--        <div class="container">--}}

{{--            <div class="row">--}}
{{--                <div class="col-lg-4">--}}
{{--                    <div class="icon-box">--}}
{{--                        <i class="icofont-computer"></i>--}}
{{--                        <h3><a href="">Lorem Ipsum</a></h3>--}}
{{--                        <p>Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident</p>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--                <div class="col-lg-4 mt-4 mt-lg-0">--}}
{{--                    <div class="icon-box">--}}
{{--                        <i class="icofont-image"></i>--}}
{{--                        <h3><a href="">Dolor Sitema</a></h3>--}}
{{--                        <p>Minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat tarad limino ata</p>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--                <div class="col-lg-4 mt-4 mt-lg-0">--}}
{{--                    <div class="icon-box">--}}
{{--                        <i class="icofont-tasks-alt"></i>--}}
{{--                        <h3><a href="">Sed ut perspiciatis</a></h3>--}}
{{--                        <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur</p>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}

{{--        </div>--}}
{{--    </section>--}}
    <!-- End Featured Section -->

    <!-- ======= About Section ======= -->
{{--    <section id="about" class="about">--}}
{{--        <div class="container">--}}

{{--            <div class="row">--}}
{{--                <div class="col-lg-6">--}}
{{--                    <img src="{{asset('assets/img/about.jpg')}}" class="img-fluid" alt="">--}}
{{--                </div>--}}
{{--                <div class="col-lg-6 pt-4 pt-lg-0 content">--}}
{{--                    <h3>Voluptatem dignissimos provident quasi corporis voluptates sit assumenda.</h3>--}}
{{--                    <p class="font-italic">--}}
{{--                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore--}}
{{--                        magna aliqua.--}}
{{--                    </p>--}}
{{--                    <ul>--}}
{{--                        <li><i class="icofont-check-circled"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>--}}
{{--                        <li><i class="icofont-check-circled"></i> Duis aute irure dolor in reprehenderit in voluptate velit.</li>--}}
{{--                        <li><i class="icofont-check-circled"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate trideta storacalaperda mastiro dolore eu fugiat nulla pariatur.</li>--}}
{{--                    </ul>--}}
{{--                    <p>--}}
{{--                        Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate--}}
{{--                        velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in--}}
{{--                        culpa qui officia deserunt mollit anim id est laborum--}}
{{--                    </p>--}}
{{--                </div>--}}
{{--            </div>--}}

{{--        </div>--}}
{{--    </section>--}}
    <!-- End About Section -->

    <!-- ======= Services Section ======= -->
    <section id="services" class="services">
        <div class="container">

            <div class="section-title  " data-aos="fade-up">
                <h2 class="animate__animated animate__rubberBand">We Provide Services</h2>
            </div>

            <div class="row">
                @foreach($provideServices as $provideService)
                <div class="col-lg-4 col-md-6 d-flex align-items-stretch" 
                     data-aos="fade-right"
                     data-aos-easing="ease-in-sine"
                     style="text-overflow: ellipsis;white-space: nowrap;overflow: hidden;">
                    <i class="fas fa-chevron-right"></i>
                    <span style="margin-left: 12px;margin-top: -5px;">{{ $provideService->name }}</span>
                </div>
                @endforeach
            </div>
            <div class="row w-100 justify-content-center">
                <div class="justify-content-center d-flex mt-4 home-provide-services" data-aos="fade-up">
                    <a class="home-provide-services-btn" href="{{ route('our-services') }}">View More</a>
                </div>
            </div>
        </div>
    </section><!-- End Services Section -->

    <!-- ======= Clients Section ======= -->
    <section id="clients" class="clients">
        <div class="container" data-aos="zoom-in">

            <div class="section-title animate__animated animate__bounce">
                <h2>Clients</h2>
                {!! $frontSettings['client_description'] !!}
            </div>

            <div class="owl-carousel clients-carousel">
                @foreach($clients as $client)
                    <img src="{{ $client->logo_url }}" alt="">
                @endforeach
            </div>

        </div>
    </section>
    <!-- End Clients Section -->

</main>
<!-- End #main -->
@endsection