digital/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\FrontSettingController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\ProvideServiceController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\GalleryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/',[HomeController::class,'index'])->name('index');
Route::get('our-services',[HomeController::class,'ourService'])->name('our-services');
Route::get('about-us',[HomeController::class,'aboutUs'])->name('about-us');
Route::get('contactus',[HomeController::class,'contactUs'])->name('contactUs');
Route::get('client',[HomeController::class,'client'])->name('client');
Route::get('galleries',[HomeController::class,'gallery'])->name('galleries');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

// front settings
Route::get('setting/home', [FrontSettingController::class, 'home'])->name('front.settings.home');
Route::post('setting/home', [FrontSettingController::class, 'homeUpdate'])->name('front.settings.home.update');
Route::delete('delete-home-slider/{homePageSlider}', [FrontSettingController::class, 'deleteHomeSlider'])->name('front.settings.deleteHomeSlider');
//Route::get('get-home-hero-images',[FrontSettingController::class, 'getHomeHeroImages'])->name('get.home.hero.images');


// settings routes
Route::get('settings', [SettingController::class,'index'])->name('settings.index');
Route::post('settings', [SettingController::class,'update'])->name('settings.update');


Route::resource('provide-services', ProvideServiceController::class);
Route::post('provide-services/{provide_service}/update', [ProvideServiceController::class,'update']);

Route::resource('clients', ClientController::class);
Route::post('clients/{client}/update', [ClientController::class,'update']);

Route::resource('contact-us', ContactUsController::class);

Route::resource('gallery', GalleryController::class);
Route::post('gallery/{gallery}/update', [GalleryController::class,'update']);

digital/app/Http/Controllers/ProvideServiceController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\ProvideServiceDataTable;
use App\Http\Requests\CreateProvideServiceRequest;
use App\Http\Requests\UpdateProvideServiceRequest;
use App\Models\ProvideSerivce;
use App\Repositories\ProvideSerivceRepository;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class ProvideServiceController extends AppBaseController
{
    /** @var  ProvideSerivceRepository  $provideSerivceRepository */
    private $provideSerivceRepository;

    public function __construct(ProvideSerivceRepository $provideSerivceRepository)
    {
        $this->provideSerivceRepository = $provideSerivceRepository;
    }

    /**
     * Display a listing of the Color.
     *
     * @param Request $request
     *
     * @return View|Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            return DataTables::of((new ProvideServiceDataTable())->get())->make(true);
        }

        return view('provide_services.index');
    }

    /**
     * Store a newly created Color in storage.
     *
     * @param CreateProvideServiceRequest $request
     *
     * @return JsonResponse
     */
    public function store(CreateProvideServiceRequest $request)
    {
        $input = $request->all();

        $service = ProvideSerivce::create($input);

        if (isset($input['image']) && ! empty($input['image'])) {
            $service->addMedia($input['image'])->toMediaCollection(ProvideSerivce::IMG_PATH);
        }
//        $input = $request->all();
//
//        $color = $this->provideSerivceRepository->create($input);

        return $this->sendSuccess('Provide Serivce saved successfully.');
    }

    /**
     * Display the specified Color.
     *
     * @param ProvideSerivce $provide_service
     *
     * @return JsonResponse
     */
    public function show(ProvideSerivce $provide_service)
    {
        return $this->sendResponse($provide_service, 'Provide Serivce Retrieved Successfully.');
    }

    /**
     * Show the form for editing the specified Color.
     *
     * @param ProvideSerivce $provide_service
     *
     * @return JsonResponse
     */
    public function edit(ProvideSerivce $provide_service)
    {
        return $this->sendResponse($provide_service, 'Provide Serivce Retrieved Successfully.');
    }

    /**
     * Update the specified Color in storage.
     *
     * @param UpdateProvideServiceRequest $request
     * @param ProvideSerivce $provide_service
     *
     * @return JsonResponse
     */
    public function update(UpdateProvideServiceRequest $request,ProvideSerivce $provide_service)
    {
        $input = $request->all();
        $service = $this->provideSerivceRepository->update($input, $provide_service->id);

        if (isset($input['image']) && ! empty($input['image'])) {
            $service->clearMediaCollection(ProvideSerivce::IMG_PATH);
            $service->addMedia($input['image'])->toMediaCollection(ProvideSerivce::IMG_PATH);
        }
//        $this->provideSerivceRepository->update($request->all(), $provide_service->id);

        return $this->sendSuccess('Provide Serivce updated successfully.');
    }

    /**
     * Remove the specified Color from storage.
     *
     * @param ProvideSerivce $provide_service
     *
     * @throws Exception
     *
     * @return JsonResponse
     */
    public function destroy(ProvideSerivce $provide_service)
    {
        $provide_service->clearMediaCollection(ProvideSerivce::IMG_PATH);
        $provide_service->delete();

        return $this->sendSuccess('Provide Serivce deleted successfully.');
    }
}

digital/resources/views/provide_services/add_modal.blade.php
<div id="addModal" class="modal fade rounded-8 overflow-hidden" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create Provide Services</h5>
                <button type="button" aria-label="Close" class="close" data-dismiss="modal">×</button>
            </div>
            {{ Form::open(['id' => 'clients.store','id'=>'createForm', 'files'=>true]) }}
            <div class="modal-body">
                <div class="alert alert-danger d-none" id="validationErrorsBox"></div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        {!! Form::label('name', 'Name:') !!}<span class="text-danger">*</span>
                        {!! Form::text('name', old('name'), ['class' => 'form-control '. ($errors->has('name') ? 'is-invalid':''),'required']) !!}
                        <div class="invalid-feedback">{{ $errors->first('name') }}</div>
                    </div>
                    <div class="form-group col-sm-12">
                        <div class="row">
                            <div class="col-6 col-xl-3">
                                {{ Form::label('app_logo', 'Image'.':') }}
                                <label class="image__file-upload"> Choose
                                    {{ Form::file('image',['id'=>'image','class' => 'd-none']) }}
                                </label>
                            </div>
                            <div class="col-6 col-xl-6 pl-0 mt-1">
                                <img id='imagePreview' class="img-thumbnail thumbnail-preview"
                                     src="{{ asset('assets/img/favicon.png') }}">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="">
                    {{ Form::button('Save', ['type' => 'submit', 'class' => 'btn btn-primary', 'id' => 'btnSave','data-loading-text'=>"<span class='spinner-border spinner-border-sm mr-2'></span> Processing..."]) }}
                    <a href="{{ route('provide-services.index') }}" class="btn btn-light">Cancel</a>
                </div>
            </div>
            {{ Form::close() }}
        </div>
    </div>
</div>

digital/resources/views/provide_services/edit_modal.blade.php
<div class="modal fade" tabindex="-1" role="dialog" id="editModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit Provide Service</h5>
                <button type="button" aria-label="Close" class="close" data-dismiss="modal">×</button>
            </div>
            {{ Form::open(['id'=>'editForm', 'files' => true, 'autocomplete' => 'off']) }}
            <div class="modal-body">
                <div class="alert alert-danger d-none" id="editValidationErrorsBox"></div>
                {{ Form::hidden('provideServicesId', null, ['id' => 'provideServicesId']) }}
                <div class="row">
                    <div class="form-group col-sm-12">
                        {!! Form::label('name', 'Name:') !!}<span class="text-danger">*</span>
                        {!! Form::text('name', old('name'), ['class' => 'form-control '. ($errors->has('name') ? 'is-invalid':''),'required', 'id' => 'editName']) !!}
                        <div class="invalid-feedback">{{ $errors->first('name') }}</div>
                    </div>
                    <div class="form-group col-sm-12">
                        <div class="row">
                            <div class="col-6 col-xl-3">
                                {{ Form::label('app_logo', 'Image'.':') }}
                                <label class="image__file-upload"> Choose
                                    {{ Form::file('image',['id'=>'editImage','class' => 'd-none']) }}
                                </label>
                            </div>
                            <div class="col-6 col-xl-6 pl-0 mt-1">
                                <img id='editImagePreview' class="img-thumbnail thumbnail-preview"
                                     src="{{ asset('assets/img/favicon.png') }}">
                                <a href="#" target="_blank" id="imageUrl"></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="">
                    {{ Form::button('Save', ['type'=>'submit', 'class' => 'btn btn-primary','id' => 'btnEditSave','data-loading-text' => "<span class='spinner-border spinner-border-sm mr-2'></span> Processing..."]) }}
                    <a href="{{ route('provide-services.index') }}" class="btn btn-light">Cancel</a>
                </div>
            </div>
            {{ Form::close() }}
        </div>
    </div>
</div>

digital/resources/views/provide_services/index.blade.php
@extends('layouts.app')
@section('title')
    Provide Services
@endsection
@push('css')
    <link href="{{ asset('assets/css/jquery.dataTables.min.css') }}" rel="stylesheet" type="text/css"/>
@endpush
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Provide Services</h1>
            <div class="section-header-breadcrumb">
                <a class="btn btn-primary addProvideServicesModal">Provide Services
                    <i class="fas fa-plus"></i>
                </a>
            </div>
        </div>
        <div class="section-body">
            <div class="card">
                <div class="card-body">
                    @include('provide_services.table')
                </div>
            </div>
        </div>
    </section>
    @include('provide_services.add_modal')
    @include('provide_services.edit_modal')
    @include('provide_services.show')
@endsection
@push('scripts')
    <script>
        let provideServiceUrl = "{{ route('provide-services.index') }}";
        let provideServiceSaveUrl = "{{ route('provide-services.store') }}";
    </script>
    <script src="{{ asset('assets/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{mix('assets/js/provide_services/provide_services.js')}}"></script>
@endpush

digital/resources/views/provide_services/show.blade.php
<div class="modal fade" tabindex="-1" role="dialog" id="showModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Provide Service Details</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    @include('provide_services.show_fields')
                </div>
            </div>
        </div>
    </div>
</div>

digital/resources/views/provide_services/show_fields.blade.php
<!-- Name Field -->
<div class="form-group col-md-6">
    {!! Form::label('name', 'Name:',['class' => 'font-weight-bold']) !!}
    <p id="show_name"></p>
</div>


<div class="form-group col-md-6">
    {!! Form::label('name', 'Image:',['class' => 'font-weight-bold']) !!}
    <img src="" class="rounded-circle thumbnail-rounded img-bg" id="show_image">
</div>

<!-- Created At Field -->
<div class="form-group col-md-6">
    {!! Form::label('created_at', 'Created At:',['class' => 'font-weight-bold']) !!}
    <p id="show_created_at"></p>
</div>


<!-- Updated At Field -->
<div class="form-group col-md-6">
    {!! Form::label('updated_at', 'Updated At:',['class' => 'font-weight-bold']) !!}
    <p id="show_updated_at"></p>
</div>

digital/resources/views/provide_services/table.blade.php
<table class="table table-responsive-sm table-striped" id="provideServicesTbl">
    <thead>
    <tr>
        <th scope="col" class="pl-0  border-0 font-size-4 font-weight-semibold">Name</th>
        <th scope="col" class="pl-0  border-0 font-size-4 font-weight-semibold">Image</th>
        <th scope="col" class="pl-0  border-0 font-size-4 font-weight-semibold">Action</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
</table>